// <auto-generated />
namespace OrpalPhotoPort.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ActiveStatusAsInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActiveStatusAsInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221333502_ActiveStatusAsInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
